# -*- coding: utf-8 -*-
"""Advanced_Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/166N7puGZMRVGKWk_rlWK27qKqZizU0D4

# Advanced_Matplotlib
"""

#Importing files
from google.colab import files
uploaded = files.upload()

!ls

!unzip 'archive (4) (1).zip'

#Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("IRIS.csv")
df.head()

df['species']=df['species'].replace({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginata':2})
df.sample(5)

# aplha and color map
plt.figure(figsize=(15,7))
color_map = {
    "Iris-setosa": "red",
    "Iris-versicolor": "green",
    "Iris-virginica": "blue"
}

colors = df["species"].map(color_map)

plt.scatter(
    df["sepal_length"],
    df["petal_length"],
    c=colors,
    alpha=0.7
)
plt.colorbar()
plt.show()

# Annotations
from google.colab import files
uploaded = files.upload()

!ls

!unzip "archive (5).zip"

!ls

!ls sample_data

import pandas as pd

df = pd.read_csv("batter (1).csv")
df.head()

plt.scatter(df['avg'],df['strike_rate'])

x=[1,2,3,4]
y=[5,6,7,8]
plt.scatter(x,y)
plt.text(1,3,'point 1')
plt.text(4,6,'point 2')
plt.text(1,3,'point 3')
plt.text(4,6,'point 4')

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("batter (1).csv")

fig, ax = plt.subplots(figsize=(5,3))  # ✅ set size here

ax.scatter(df['avg'], df['strike_rate'],
           color='red', marker='+')

ax.set_title('Average vs Strike Rate')
ax.set_xlabel('avg')
ax.set_ylabel('strike_rate')

plt.show()

# Two Graphs in Same Column
fig,ax=plt.subplots(2,1,figsize=(5,3))
# first graph
ax[0].scatter(df['avg'],df['strike_rate'],color='green',marker="+")
ax[0].set_title('Average v/s strike_rate')
ax[0].set_xlabel('avg')
ax[0].set_ylabel("strike_rate")

#second graph
ax[1].hist(df['avg'],color='red')
ax[1].set_title('Average Distribution')
ax[1].set_xlabel('avg')
ax[1].set_ylabel('count')

plt.tight_layout()
plt.show()

# Adding multiple graphs in one output(method1)
fig,ax=plt.subplots(nrows=2,ncols=2,figsize=(5,3))

ax[0,0].scatter(df['avg'],df['strike_rate'],color='red')
ax[0,1].scatter(df['avg'],df['runs'])
ax[1,0].hist(df['avg'])
ax[1,1].hist(df['runs'])

# Adding multiple graphs in one output(method2)
fig=plt.figure()
ax1=fig.add_subplot(2,2,1)
ax1.scatter(df['avg'],df['strike_rate'],color='green')

ax2=fig.add_subplot(2,2,2)
ax2.hist(df['runs'])

ax3=fig.add_subplot(2,2,3)
ax3.hist(df['avg'])

# 3D scatter plots
fig=plt.figure()
ax=plt.subplot(projection='3d')
ax.scatter3D(df['runs'],df['avg'],df['strike_rate'])
ax.set_title("Ipl batsman analysis")
ax.set_xlabel('runs')
ax.set_ylabel('Avg')
ax.set_zlabel('strike_rate')
plt.show()

# 3D line plots
x=[10,20,30,40]
y=[0,10,13,0]
z=[0,13,20,9]
fig=plt.figure()
ax=plt.subplot(projection='3d')
ax.scatter3D(x,y,z,s=[100,100,100,100])
ax.plot3D(x,y,z,color='red')

# 3D surface plots
x=np.linspace(-10,10,100)
y=np.linspace(-10,10,100)
xx,yy=np.meshgrid(x,y)
z=xx**2+yy**2
z.shape
fig=plt.figure(figsize=(5,3))
ax=plt.subplot(projection='3d')
p=ax.plot_surface(xx,yy,z,cmap='viridis')
fig.colorbar(p)

# counter plots
z=np.sin(xx) + np.cos(yy)
fig=plt.figure(figsize=(5,3))
ax=plt.subplot()
p=ax.contourf(xx,yy,z,cmap='viridis')
fig.colorbar(p)

# Heatmap
import seaborn as sns
import matplotlib.pyplot as plt

# Select numeric columns
numeric_df = df.select_dtypes(include='number')

# Create correlation matrix
corr = numeric_df.corr()

# Plot heatmap
plt.figure(figsize=(6,4))
sns.heatmap(corr,
            annot=True,
            cmap='viridis',
            fmt=".2f")

plt.title("Correlation Heatmap")
plt.show()

# pandas plot
s=pd.Series([1,2,3,4,5,6,7])
plt.figure(figsize=(5,3))
s.plot(kind='pie')

# scatter plaots
plt.figure(figsize=(5,3))
df.plot(kind='scatter',x='avg',y='strike_rate')

# line plots
import matplotlib.pyplot as plt

# Line plot of runs
df.plot(x='batter', y='runs', kind='line', figsize=(5,3))

plt.xticks(rotation=45)
plt.title("Runs by Batter")
plt.show()

# bar chart
df.groupby('batter')['strike_rate'].mean().plot(kind='bar', figsize=(8,4))

plt.title("Average Strike Rate by Batter")
plt.ylabel("Strike Rate")
plt.xticks(rotation=45)
plt.show()

# stacked bar chart
df.plot(kind='bar',stacked=True)

# Histogram
df['strike_rate'].plot(kind='hist', bins=5, figsize=(6,4))
df

# pie chart
df['batter'].value_counts().plot(kind='pie',
                                 autopct='%1.1f%%',
                                 figsize=(5,3))

plt.title("Batter Distribution")
plt.ylabel("")
plt.show()

# Multiple pie chart
df[['runs','strike_rate']].plot(kind='pie',subplots=True,autopct='%1.1f%%',figsize=(5,3))

# stocks datatset
import pandas as pd
import matplotlib.pyplot as plt

# Create dataset
data = {
    "Date": pd.date_range(start="2024-01-01", periods=10, freq='D'),
    "TCS": [3600, 3620, 3580, 3650, 3700, 3680, 3720, 3750, 3780, 3800],
    "Infosys": [1500, 1520, 1490, 1510, 1530, 1550, 1540, 1560, 1580, 1600],
    "Reliance": [2500, 2520, 2480, 2510, 2550, 2580, 2600, 2620, 2650, 2700]
}

stocks = pd.DataFrame(data)

# Set Date as index
stocks.set_index("Date", inplace=True)

print(stocks.head())

# using stocks
stocks.plot(kind='line', subplots=True, figsize=(5,3))
plt.show()

# on multi Index dataframes
import pandas as pd
import matplotlib.pyplot as plt

# Create MultiIndex
index = pd.MultiIndex.from_product(
    [[2023, 2024], ['Q1', 'Q2']],
    names=['Year', 'Quarter']
)

# Create DataFrame
df = pd.DataFrame({
    'Sales': [100, 150, 200, 250],
    'Profit': [20, 30, 40, 50]
}, index=index)

print(df)

df.plot(kind='line', figsize=(8,5), marker='o')
plt.title("Sales & Profit over Year-Quarter")
plt.ylabel("Value")
plt.show()