# -*- coding: utf-8 -*-
"""Data Cleaning Toolkit using NumPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PkF49LXYAnBt_26M0qFn6lgn1SFm1tL9
"""

# Data Cleaning Toolkit using Numpy

#Problem Statement
#Real-world datasets contain missing values, outliers, and inconsistent data.
#This project demonstrates how to clean raw numerical data using only NumPy.

#Create Sample Raw Dataset
import numpy as np
dataset=np.array([33,10,2000,98,np.nan,76,35,14,np.nan,88])
print(dataset)

#Detect Missing Values
check=np.isnan(dataset)
print(check)

#Replace Missing Values
mean_val=np.nanmean(dataset)
replace=np.where(np.isnan(dataset),mean_val,dataset)
print(replace)

# Detect Outliers
print("Max value is",np.max(dataset))

#Deleting nan values
clean_data=dataset[~np.isnan(dataset)]
print(clean_data)

# Clip Extreme Values (Data Cleaning)
clip=np.clip(clean_data,1,100)
print(clip)

# Statistical Summary
print(np.std(clip))
print(np.mean(clip))

# Conclusion Section
# - created a sample dataset
# - detected and replaced missing Values
# - detected outliers
# - deletinh nan Values
# - clipped extreme values
# - Finally concluded with statistical summary

