# -*- coding: utf-8 -*-
"""Exploratory_Data_Analysis(EDA).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FhejgI-t4iVAbed3oUxw0cO_fnPGiWq

# EDA
"""

# Data Analysis Process

#1️⃣ Asking Questions
#2️⃣ Data Wrangling (Data Cleaning & Preparation)
#3️⃣ Exploratory Data Analysis (EDA)
#4️⃣ Drawing Conclusions
#5️⃣ Communicating Results

from google.colab import files
uploaded = files.upload()

!unzip "archive (13) (1).zip"

import pandas as pd

df = pd.read_csv("train.csv")
df.head()

# Basic Overview
df['Age'].describe()

df['Age'].plot(kind='hist',bins=30)

df['Age'].plot(kind='kde')

df['Age'].skew()

df['Age'].plot(kind='box')

df[df['Age']>65]

df['Age'].isnull().sum()/len(df['Age'])

# Target Variable Analysis
import seaborn as sns
import matplotlib.pyplot as plt
df['Survived'].value_counts()
df['Survived'].value_counts(normalize=True)

sns.countplot(x='Survived', data=df)
plt.title("Survival Distribution")
plt.show()

# Univariate Analysis — Numerical Features
df['Age'].describe()

df['Age'].plot(kind='hist', bins=30)
plt.title("Age Distribution")
plt.show()

df['Age'].plot(kind='kde')
plt.title("Age KDE")
plt.show()

print("Skewness:", df['Age'].skew())

df['Age'].plot(kind='box')
plt.title("Age Boxplot")
plt.show()

print("Missing %:", df['Age'].isnull().sum()/len(df))

# Missing Value Analysis
missing_percent = (df.isnull().sum()/len(df))*100
missing_percent.sort_values(ascending=False)

# Bivariate Analysis — Numerical vs Target
# Age vs Survived
sns.boxplot(x='Survived', y='Age', data=df)
plt.title("Age vs Survival")
plt.show()

# Fare vs Survived
sns.boxplot(x='Survived', y='Fare', data=df)
plt.title("Fare vs Survival")
plt.show()

# Bivariate Analysis — Categorical vs Target
# Sex vs Survived
sns.countplot(x='Sex', hue='Survived', data=df)
plt.title("Gender vs Survival")
plt.show()

pd.crosstab(df['Sex'], df['Survived'], normalize='index')*100

# Pclass vs Survived
sns.countplot(x='Pclass', hue='Survived', data=df)
plt.title("Class vs Survival")
plt.show()

pd.crosstab(df['Pclass'], df['Survived'], normalize='index')*100

# Correlation Heatmap
plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

# Outlier Detection Using IQR
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

outliers = df[(df['Age'] < lower) | (df['Age'] > upper)]
print("Number of Age Outliers:", len(outliers))

# Feature Engineering
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

sns.boxplot(x='Survived', y='FamilySize', data=df)
plt.title("Family Size vs Survival")
plt.show()

#-----------------------
# Final Summary Insights
#------------------------
# 1.Distribution Insight:
#The variable Fare shows a highly right-skewed distribution with strong positive skewness. Extreme values suggest the presence of a small group of passengers who paid significantly higher ticket prices compared to the majority. Appropriate transformation such as log transformation may improve model stability and reduce the impact of outliers.
#The variable Age shows a moderately right-skewed distribution with slight positive skewness. Extreme values suggest the presence of elderly passengers at the upper range. Appropriate preprocessing such as median imputation and age binning may improve model robustness.

# 2.Relationship Insight:
#There is a positive correlation between Fare and Survival, indicating that as Fare increases, survival probability tends to increase. This suggests socioeconomic status may significantly influence the target variable.
#There is a negative correlation between Pclass and Survival, indicating that as passenger class number increases (1 → 3), survival probability tends to decrease. This further confirms the impact of economic class on survival outcomes.

# 3.Categorical Comparison:
#The category Female demonstrates a significantly higher average survival rate compared to Male, suggesting that gender played an important role in determining survival outcomes.
#Similarly, First Class passengers demonstrate higher survival rates compared to Third Class passengers, suggesting passenger class strongly influenced access to safety measures.

# 4.Feature Redundancy Insight:
#Fare and Pclass exhibit moderate negative correlation, indicating potential multicollinearity since both represent socioeconomic status. Careful feature selection or regularization may be required to improve model interpretability and prevent redundancy.







