# -*- coding: utf-8 -*-
"""Groupby in pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aPXL2u-mLmu1ch-FiFwh65NCd0mM1u_g

# Groupby in pandas
"""

#importing libraries
import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

!ls

!unzip "archive (1).zip"

#reading files
import pandas as pd

df = pd.read_csv('Movie Dataset.csv')
df

# calculate diffrent movie genre and calculate its sum
g=df.groupby('Genre').sum()
g

# calculate top 3 genre by popularity
df.groupby('Genre')['Popularity'].sum().sort_values(ascending=False).head(3)

# Top 5 genres by average rating
df['Vote_Average'] = pd.to_numeric(df['Vote_Average'], errors='coerce')
df.groupby('Genre')['Vote_Average'].mean().sort_values(ascending=False).head(5)

#nOTE:errors='coerce'->don't show error if its there show 'nan'

# Top 5 genres with highest total vote count
df.groupby('Genre')['Vote_Count'].sum().sort_values(ascending=False).head(5)

# Genre with highest average popularity
df.groupby('Genre')['Popularity'].mean().sort_values(ascending=False).head(1)

"""## Important functions"""

# len
len(df.groupby('Genre'))

# nunique
df['Genre'].nunique()

# position
genre=df.groupby('Genre')
genre.first()
genre.last()
genre.nth(6)

#value_count
df['Genre'].value_counts()

# get group
df[df['Genre']=='Horror']

# describe
df.describe()

# sample
df.sample(2,replace=True)

# working with dictinaries
df.groupby('Genre').agg(
    avg_popularity=('Popularity','mean'),
    avg_rating=('Vote_Average','mean'),
    total_votes=('Vote_Count','sum')
)

# describe
df.describe()

# passing list in aggregate functions
df.select_dtypes(include='number').agg(['min','max','mean','sum'])

# Looping on groups

# Print number of movies in each genre using loop
for genre,data in df.groupby('Genre'):
  print(genre,len(data))

# Print first movie title from every genre
for genres,data in df.groupby('Genre'):
  print(genre,"->",data['Title'].iloc[0])

# Find the average popularity of movies for each language
df.groupby('Original_Language')['Popularity'].mean()

"""## More Practice Questions(Groupby + Data Analysis)"""

#PART 1 — BASIC GROUPBY PRACTICE
# 1.Total movies per genre
df.groupby('Genre')['Title'].count()

df['Genre'].value_counts()

#2. Average vote rating per genre
df.groupby('Genre')['Vote_Average'].mean()

# 3.Total popularity per language
df.groupby('Original_Language')['Popularity'].sum()

# 4.Most popular genre
popularity=df.groupby('Genre')['Popularity'].sum()
final_pop=popularity.sort_values(ascending=False)
final_pop.head(1)

# 5.Average vote count per language
df['Vote_Count'] = pd.to_numeric(df['Vote_Count'], errors='coerce')
df.groupby('Original_Language')['Vote_Count'].mean()

#  PART 2 — FUNCTIONS PRACTICE
# 1.Create rating category column
def rating_category(vote):
    if vote >= 8:
        return 'Excellent'
    elif vote >= 6:
        return 'Good'
    else:
        return 'Average'

df['Rating_Category'] = df['Vote_Average'].apply(rating_category)
df

# 2.Create popularity level column
def popularity_column(pop):
  if pop>2000:
    return "Trending!"
  elif pop>1000:
    return "popular"
  else:
    return "normal"

df['popularity_column']=df['Popularity'].apply(popularity_column)
df

# 3.Popularity difference from genre average
df['Popularity_difference'] = df['Popularity'] - df.groupby('Genre')['Popularity'].transform('mean')
df

#  PART 3 — ADVANCED GROUPBY CHALLENGES

# 1.Multi aggregation.Find:avg popularity,avg rating, total votes using .agg()
avg_popularity=df.groupby('Genre')['Popularity'].mean()

#2. Top movie per genre (highest popularity)
df_expanded=df.assign(Genre=df['Genre'].str.split(',').explode('Genre'))
top_movies=df_expanded.loc[df_expanded.groupby('Genre')['Popularity'].idxmax()]
top_movies=top_movies[['Genre','Title','Popularity']].reset_index(drop=True)
print(top_movies)

# 3. Movies count per year per language
df['Release_Date'] = pd.to_datetime(df['Release_Date'], errors='coerce')
df['Year'] = df['Release_Date'].dt.year
movies_count = df.groupby(['Year', 'Original_Language']).size().reset_index(name='Movie_Count')
movies_count = movies_count.sort_values(['Year', 'Movie_Count'], ascending=[True, False])
print(movies_count)

# 4.Count movies by:Genre + Original_Language

# Split multiple genres and explode
df_expanded = df.assign(Genre=df['Genre'].str.split(', ')).explode('Genre')
# Group by Genre and Original_Language, then count movies
movies_count = df_expanded.groupby(['Genre', 'Original_Language']).size().reset_index(name='Movie_Count')
# Sort
movies_count = movies_count.sort_values(['Genre', 'Movie_Count'], ascending=[True, False])
print(movies_count)

# 5.Find percentage contribution of each movie to genre popularity.
df_expanded = df.assign(Genre=df['Genre'].str.split(', ')).explode('Genre')
genre_total = df_expanded.groupby('Genre')['Popularity'].transform('sum')
df_expanded['Contribution_Percent'] = (df_expanded['Popularity'] / genre_total) * 100
result = df_expanded[['Title', 'Genre', 'Popularity', 'Contribution_Percent']]
print(result.head(10))

#6.Detect genres with highest rating variance.

# Step 0: Make sure Vote_Average is numeric
df['Vote_Average'] = pd.to_numeric(df['Vote_Average'], errors='coerce')
# Step 1: Drop rows where Vote_Average is NaN (optional but safer)
df = df.dropna(subset=['Vote_Average'])
# Step 2: Split genres and explode
df_expanded = df.assign(Genre=df['Genre'].str.split(', ')).explode('Genre')
genre_rating_std = df_expanded.groupby('Genre')['Vote_Average'].std()
genre_rating_std = genre_rating_std.sort_values(ascending=False)
print(genre_rating_std.head(10))

#7.Sort movies inside each genre by popularity.
df_expanded=df.assign(Genre=df['Genre'].str.split(',').explode('Genre'))
df_sort=df_expanded.sort_values(['Genre','Popularity'],ascending=[True,False])
print(df_sort[['Genre','Title','Popularity']].head(20))

#8.Get top 3 movies from each genre.
df_expanded = df.assign(Genre=df['Genre'].str.split(',')).explode('Genre')
df_sort=df_expanded.sort_values(['Genre','Popularity'],ascending=[True,False])
top_3_movies=df_sort.groupby('Genre').head(3)
print(top_3_movies[['Genre','Title','Popularity']])

#9. Movie closest to genre average rating.
df_expanded = df.assign(Genre=df['Genre'].str.split(', ')).explode('Genre')
df_expanded['Vote_Average'] = pd.to_numeric(df_expanded['Vote_Average'], errors='coerce')
df_expanded = df_expanded.dropna(subset=['Vote_Average'])
df_expanded['Diff'] = abs(df_expanded['Vote_Average'] - df_expanded.groupby('Genre')['Vote_Average'].transform('mean'))
closest_movies = df_expanded.loc[df_expanded.groupby('Genre')['Diff'].idxmin()]
print(closest_movies[['Genre', 'Title', 'Vote_Average']])

#10. Identify outlier movies in popularity within each genre
# Split genres and explode
df_expanded = df.assign(Genre=df['Genre'].str.split(', ')).explode('Genre')
# Make sure Popularity is numeric
df_expanded['Popularity'] = pd.to_numeric(df_expanded['Popularity'], errors='coerce')
df_expanded = df_expanded.dropna(subset=['Popularity'])
# Detect outliers: more than 2 std away from genre mean
df_expanded['Is_Outlier'] = abs(df_expanded['Popularity'] -
                                df_expanded.groupby('Genre')['Popularity'].transform('mean')) > \
                                2 * df_expanded.groupby('Genre')['Popularity'].transform('std')
# Show outlier movies
print(df_expanded[df_expanded['Is_Outlier']][['Genre', 'Title', 'Popularity']])









