# -*- coding: utf-8 -*-
"""Image Processing using NumPy Arrays.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/190gZgvACnmQIkyh73mfjtGClK1jOXz5A
"""

# Image Processing using NumPy Arrays

# Problem Statement

# - Images are represented as numerical arrays.
# - This project demonstrates basic image processing operations using only NumPy.

#Create Sample Image
import numpy as np
image = np.array([
    [50, 80, 100],
    [120, 150, 200],
    [30, 60, 90]
])

print(image)

# -> Thinking this as pixel brightness values.

# Increase Brightness
bright_image =np.clip(image+50,0,255)
print(bright_image)

# -> Here the concept of braodcasting is used here: 50 is added because-"Higher the image value,higher is the Brightness"

# Decrease Brightness
Dull_image=np.clip(image-40,0,255)
Dull_image

# ->Concept:Broadcasting is used here:40 is subtracted because-"Lower the value duller the image"

#Flip Image
flipped_image_ver=np.flip(image,axis=1)
print(flipped_image_ver)
# -> Here the matrix is flipped vertically

flipped_image_horz=np.flip(image,axis=0)
print(flipped_image_horz)
# -> Here the matrix is flipped horizontally

#Rotate Image
rotated_image=np.rot90(image)
rotated_image
# ->Rotates the image

# Contrast Adjustment
contrast=np.clip(image*1.5,0,255)
contrast#

# ->Contarst is used to make the image look more vivid

#Conclusion Section
# ->Numpy allows data manipulation using vectorised operations,slicing and broadcasting
# ->operations like brightness changes,contrast adjustments
# ->flipping and rotations are easily done using Numpy making work fast to complete.

