# -*- coding: utf-8 -*-
"""Important Dataframe methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WP5zUFgKMCdW6zRP6iYDRO5wpMKxKE9K

# Important Dataframe methods
"""

#Importing libraries
import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

!ls

# Unzip the file
!unzip archive.zip

#read files
ipl=pd.read_csv('matches.csv')
ipl

# creating dataframes
marks=pd.DataFrame([
    [100,80,10],
    [90,70,7],
    [120,100,14]
],columns=['iq','marks','package'])

marks

# 1.value_counts()
ipl['toss_decision'].value_counts().plot(kind='pie')

#arithrmatic operations
total=(ipl['team1'].value_counts() + ipl['team2'].value_counts()).sort_values(ascending=False)
total

# 2.sort_values
#sorting single column
ipl.sort_values('date',ascending=False)

ipl.columns

# Sorting multiple columns
ipl.sort_values(by=['toss_winner','target_overs'],ascending=[True,False])

# 3.sort_index
ipl.sort_index(ascending=False)

# 4.set_index
ipl.set_index('venue',inplace=True,drop=False)

#nOTE:drop->do not remove venue from the dataframe

#5.reset_index
ipl.reset_index(inplace=True, drop=True)

#6.rename
ipl.rename(columns={'player_of_match':'mvp'},inplace=True)
ipl

# 7.len
len(ipl['season'].unique())

# 8.null
ipl[ipl['mvp'].isnull()]

# 9.notnull
ipl['mvp'].notnull()

# 10.hasnans
ipl['mvp'].hasnans

# 11.dropna
ipl_clean = ipl.dropna(subset=['mvp'])
ipl_clean

# 12.fillna
ipl['mvp'].fillna('No MVP',inplace=True)
ipl

# 13.drop_duplicates
temp=pd.Series([1,2,3,1,4,3])
temp.drop_duplicates()

# 14.drop
ipl.drop(columns=['umpire1','umpire2'])

# 15.apply
temp=pd.Series([10,20,30,25,60])
temp

def sigmoid(value):
  return 1/1+np.exp(-value)
temp.apply(sigmoid)