# -*- coding: utf-8 -*-
"""Merge_join_concat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cPbGm9AArSM-iHPa0xtK7_n-QfMpYtAd

# Merge_join_concat in pandas
"""

# DATASET: SuperMart Sales Data
import pandas as pd
import numpy as np

#Customers Dataset
customers = pd.DataFrame({
    'customer_id': [1,2,3,4,5,6],
    'name': ['Asha','Ravi','Neha','Arjun','Priya','Karan'],
    'city': ['Delhi','Mumbai','Delhi','Chennai','Mumbai','Chennai']
})
print(customers)

#Products Dataset
products = pd.DataFrame({
    'product_id': [101,102,103,104],
    'product_name': ['Laptop','Phone','Tablet','Headphones'],
    'category': ['Electronics','Electronics','Electronics','Accessories'],
    'price': [50000,20000,30000,5000]
})

print(products)

#Orders — January
import pandas as pd

orders_jan = pd.DataFrame({
    'order_id': [1,2,3,4],
    'customer_id': [1,2,3,4],
    'product_id': [101,102,103,104],
    'quantity': [1,2,1,3]
})

print(orders_jan)

#Orders — February
orders_feb = pd.DataFrame({
    'order_id': [5,6,7,8],
    'customer_id': [5,6,1,2],
    'product_id': [102,101,104,103],
    'quantity': [1,1,2,1]
})
print(orders_feb)

#Tasks
# 1.Combine January & February orders
order=pd.concat([orders_jan,orders_feb],ignore_index=True)
print(order)

#2.Merge Orders + Customers
orders_customers = pd.merge(
    orders,
    customers,
    on='customer_id',
    how='left'
)
print(orders_customers)

#3.Merge With Products
final_data = pd.merge(
    orders_customers,
    products,
    on='product_id',
    how='left'
)

print(final_data)

from google.colab import files
uploaded = files.upload()

!ls

!unzip "archive (2).zip"

# Importing Student performace dataset
import pandas as pd

df = pd.read_csv("Student_Performance.csv")
df

df.info()

df.describe()

student_info = df[[
    "student_id",
    "age",
    "gender",
    "school_type",
    "parent_education"
]]

scores = df[[
    "student_id",
    "math_score",
    "science_score",
    "english_score",
    "overall_score",
    "final_grade"
]]

pd.merge(student_info, scores , on='student_id', how='inner')

# Inner Join
inner=student_info.merge(scores,on='student_id',how='inner')
inner.shape

# Left Join
left = student_info.merge(scores,on='student_id',how='left')
left

# Outer Join
outer=student_info.merge(scores,on='student_id',how='outer')
outer

# overall_score > 85 and grade = "a"
merged=student_info.merge(scores,how='inner')
result=merged[(merged['overall_score']>85 ) &
(merged['final_grade']=='a')]
result
result[['student_id','gender','overall_score']]

# Grade = "f" AND attendance < 60
student=df[['student_id','final_grade']]
attendeance=df[['student_id','attendance_percentage']]
merged=student.merge(attendeance,on='student_id')
result = merged[
    (merged["attendance_percentage"] < 60) &
    (merged["final_grade"] == "f")
]
result.head()

# Average overall_score by gender
gender=df[['student_id','gender','overall_score']]
gender.groupby('gender')['overall_score'].mean()

# Private school students scored > 75
result=df[
(df['school_type']=='private')&
(df['overall_score']>75)
]
result

# Highest average by parent_education
df.groupby('parent_education')['overall_score'].mean().sort_values(ascending=False)

# No internet but scored > 80
result=df[
(df['internet_access']=='no')&
(df['overall_score']>80)
]
result

# Remove 300 rows and test joins
scores_small=scores.iloc[:-300]
scores_small
inner=student_info.merge(scores_small,on='student_id',how='inner')
left=student_info.merge(scores_small,on='student_id',how='left')
print(inner)
print(left)

# Duplicate Keys Test
duplicate = student_info.iloc[:5]
duplicate
test = pd.concat([student_info, duplicate])
test
merged = test.merge(scores, on="student_id")
merged.shape

# Attendance Bonus System
bonus=df[['student_id','attendance_percentage','overall_score']].copy()
bonus["bonus"]=bonus['attendance_percentage'].apply(lambda x:5 if x>90 else 0)
bonus["new_score"]=bonus['overall_score']+bonus['bonus']
bonus.sort_values('new_score',ascending=False).head()

# note:Use .copy() when slicing before modifying columns to avoid SettingWithCopyWarning

# Top 5 per school_type
df.sort_values('overall_score',ascending=False)
df.groupby('school_type').head(5)

# Study hours > 6 but score < 50
result=[(df['study_hours']>6)&
        (df['overall_score']<50)]
result

#nOTE:
🎯 What I Learned
✔ How to merge
✔ How left/inner differ
✔ Handling missing values
✔ Duplicate key behavior
✔ Real-world logic

