# -*- coding: utf-8 -*-
"""MultiIndex Series and Dataframes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P0EoLBiAoTEbrAbBZQm0NLEYsHg7murF

#  MultiIndex Series and Dataframes
"""

import pandas as pd
import numpy as np

#MultiIndex Series
index=pd.MultiIndex.from_tuples(
    [('Math','Himani'),('Math','Navami'),('gumani','science'),('himki','english')],
    names=['subject','names']
    )
scores = pd.Series([95, 85, 90, 80], index=index)
print(scores)

# Access all Math scores
math_scores = scores.loc['Math']
print(math_scores)

# Access all scores of student himani
hima_scores=scores.xs('Himani',level='names')
print(hima_scores)

# nOTE:'xs' used to access all level scores

# Access gumani’s Science score
a=scores.loc[('gumani','science')]
print(a)

# Convert the Series to a DataFrame with column name "Score"
scores_df=scores.to_frame(name='score')
print(scores_df)

# If you haven't reset yet
scores_df = scores.to_frame(name='Score')  # Series → DataFrame
scores_reset = scores_df.reset_index()      # MultiIndex → normal columns
scores_reset

# Reset the index so Subject and Student become normal columns
scores_df=scores_df.reset_index()
print(scores_df)

# creating a series with multiIndex object
MultiIndex=pd.MultiIndex.from_product([['CSE','ECE'],[2019,2020,2021,2022]],names=['Branch','Year'])
s=pd.Series([1,2,3,4,5,6,7,8],index=MultiIndex)
s

# unstack
s.unstack()

# Convert Series to DataFrame
df = s.to_frame(name='Value')
# Now use stack (if you had a column level you wanted to stack)
stacked = df.stack()  # Usually for DataFrames with column MultiIndex
print(stacked)

# MultiIndexing from column prespective
b=pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0]
    ],
    index=[2019,2020,2021,2022],
    columns=[('CSE','A'),('CSE','B'),('ECE','A'),('ECE','B')]
)
b

# nOTE:columns for cols and index for rows

#stacking and unstacking
b.unstack()

#nOTE:This will convert into dataframe
#This is used for long and wide formats

"""# Working with multiIndex Dataframes"""

# 1.head
b.head()

# 2.shape
b.shape

# 3.info
b.info()

# 4.duplicated
b.duplicated()

# 5.isnull
b.isnull()

import pandas as pd

multi_index = pd.MultiIndex.from_product(
    [['CSE','ECE'], ['2019','2020','2021','2022']],
    names=['Branch','Year']
)

s = pd.Series([10,20,30,40,50,60,70,80], index=multi_index)
df = s.to_frame(name='Value')

# Extracting Data

# Single row
df.loc[('CSE','2019')]

# Multiple row
df.loc[('CSE','2020'):('ECE','2020'):2]

# USING iloc
df.iloc[0]
df.iloc[0::2]

# Extracting cols
df.stack().loc[('CSE','2022')]

# Sort_index
df.sort_index(ascending=False)

#Transpose
df.T

# swap levels
df_swap = df.swaplevel('Branch','Year', axis=0)
print(df_swap)

#Long V/S Wide Data

# 1.wide->Has single row with multiple columns and used in databases
# 2.long->Has same no of rows and columns and used in datalakes
# 3.There comes another concept called melt and pivot
# 4.melt ->converts wide to long
# 5.pivot->converts long to wide

# melt
# Syntax:melt(index,rows,columns)
pd.DataFrame({'cse':[120],'ece':[100],'mech':[50]})
melted=df.melt(var_name='branch',value_name='num_student')
print(melted)

df = pd.DataFrame({
    'Branch': ['CSE','ECE','MECH'],
    '2019':[120,100,50],
    '2020':[130,110,60]
})

melted = df.melt(id_vars='Branch',
                 var_name='Year',
                 value_name='Students')

melted

# pivoted
# Syntax:melt(index,rows,columns)
pivoted = melted.pivot(index='Branch',
                       columns='Year',
                       values='Students')

pivoted

# Concepts to be used:

# > Use .loc[] for selecting by first level
# > Use .xs() for selecting by level
# > Use .to_frame() to convert Series → DataFrame
# > Use .reset_index() to flatten MultiIndex



