# -*- coding: utf-8 -*-
"""numpy_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vD5uFftAv1rMhc20txC2lMs4iRJpMC5m
"""

import numpy as np

#1D array
a=np.array([1,2,3])

#2D array
b=np.array([[1,2,3],[4,5,6]])

#3D array
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

np.array([1,2,3],dtype=float)

np.arange(1,11)

np.arange(1,11,2)

np.arange(1,11).reshape(5,2)

np.arange(1,13).reshape(5,5) #--> no.of elements shud be present in the array

np.ones((3,4))

np.zeros((4,5))

np.random.random((3,4))

np.linspace(-10,10,10)

np.identity(3)

a1=np.arange(10)
a1

a2=np.arange(12,dtype=float).reshape(3,4)
a2

a3=np.arange(8).reshape(2,2,2)
a3

a1.ndim

a2.ndim

a1.shape

a3.size

a2.itemsize

a1.dtype

a3.astype(np.int16)

#Array operations
#(1)scalar operations
a1*2
a1+2
a1**2

#Relational operators
a2==15
a2>15

#vector operators
a1**2

#Array Functions
a1=np.random.random((3,3))
a1=np.round (a1*100)
a1
np.max(a1)
np.sum(a1)

np.max(a1,axis=0)

#Statistical operations # Row->0 and col->1
np.mean(a1)
np.median(a1,axis=1)

#Dot products
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

#Indexing
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a3

a3[1,0,0]

a2

a2[1,1]

#Slicing
a1

a1[2:5]

a2

a2[2,:]

a2[::2,0::3]

a2[::2,1::2]

a2[1:,2:]

np.transpose(a2)

for i in a1:
  print(i)

a2.ravel()

#hstack
a4 = np.arange(12, 24).reshape(3, 4)  # shape (3,4)
a6 = np.arange(12, 24).reshape(3, 4)  # reshape to match rows
result = np.hstack((a4, a6))
print(result)

#vstack
np.vstack((a4,a6))

#hsplit
np.hsplit(a4,2)

#vsplit
np.vsplit(a6,3)

#Indexing
a4 = np.arange(12).reshape(3,4)
a4

#Fancy Indexing
a4[:,[0,1,3]]

b1 = np.random.rand(1, 100, 24).reshape(100, 24)
print(b1.shape)

b1<50

b1%6==0

#Broadcasting
#same shape
import numpy as np
a=np.arange(6).reshape(2,3)
b=np.arange(6,12).reshape(2,3)
print(a)
print(b)
print(a+b)

#diff shape
a=np.arange(6).reshape(2,3)
b=np.arange(3).reshape(1,3)
print(a)
print(b)
print(a+b)

#working with missing values
a=np.array([1,2,3,np.nan,6])
a

np.isnan(a)

#Plotting graphs
import matplotlib.pyplot as plt
x=np.linspace(-10,10,100)
y=x
plt.plot(x,y)

#Numpy tricks
a=np.random.randint(1,100,15).reshape(3,5)
a

np.sort(a)[::-1]

np.append(a,200)

e=np.array([1,2,1,3,2,4,5,5,6,6,4])
np.unique(e)

b=([3,5,6,79,8,98,67])
int(np.argmax(b))

np.percentile(b,100)

float(np.percentile(b,0))

np.flip(b)

items=[19,29,56,78]
np.isin(b,items)

import numpy as np
b =np.array([3,5,6,79,8,98,67])
np.put(b, [0,1], [110,555])
print(b)

np.delete(b,[0,1])

np.histogram(b,bins=[10,20,30,40,50,60,70,80,90])

np.clip(b,3,98)