# -*- coding: utf-8 -*-
"""pandas_Dataframes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124knj_fHHaTtJyDX3okFkO6tk8aZlqT1

# Starting with pandas Dataframes
"""

# creating dataframes
import pandas as pd
import numpy as np
student_data=[
    [100,80,10],
    [90,70,20],
    [120,100,14]
]
a=pd.DataFrame(student_data,columns=['IQs','marks','packages'])
a

#creating dataframes using dictionaries
student_dict={
    'fruits':['apple','mango','chikku'],
    'places':['rajasthan','himalayas','gujarat'],
    'animals':['cat','dog','rabbit']
}
student_dict1=pd.DataFrame(student_dict)
student_dict1

from google.colab import files

uploaded = files.upload()

import os
os.listdir()

# unzip the archive
!unzip archive.zip

!ls

# reading files
import pandas as pd
ipl= pd.read_csv('deliveries.csv')
ipl.head()

#shape
ipl.shape

#dtypes
ipl.dtypes

#index
ipl.index

#columns
ipl.columns

#values
ipl.values

#head
ipl.head(3)

#tail
ipl.tail(2)

#sample
ipl.sample(3)

#info->gives summary of data
ipl.info()

#describe->gives summary statistics of data
ipl.describe()

#isnull
ipl.isnull().sum()

#duplicated
ipl.duplicated().sum()

#rename
a.rename(columns={'marks':'percent','package':'lpa'},inplace=True)

a

"""## Math methods"""

#sum
a.sum()

a.sum(axis=1)
#nOTE:axis=0 -> columns
#     axis=1 -> rows

#mean
a.mean(axis=0)

#nOTE:This works same for min,max,std,var,median

#To select one row->series
#To select multiple columns->dataframes

#selecting mulyiple columns
ipl[['batting_team','bowler','bowler']]

# selecting rows in dataframe
ipl.iloc[:5]

# Fancy indexing
#iloc->index positions
ipl.iloc[[0,4,5]]

# loc->helps in label indexing
ipl.loc[ipl['batter']=='VR Iyer']

ipl.loc[(ipl['batter']=='BB McCullum')|(ipl['batter']=='VR Iyer')]

# Exercises
# 1.Find the total runs scored by VR Iyer in all matches.
ipl.loc[ipl['batter']=='VR Iyer','total_runs'].sum()

# 2.Get all deliveries for match_id = 1426312.
ipl.loc[ipl['match_id']==1426312]

# 3.How many unique balls were bowled in the dataset?
ipl['bowler'].nunique()
#nOTE:unique->shows all the unique items
#     nuique->shows the number of unique items

#  Drop duplicates and show first 5 unique deliveries
a=ipl.drop_duplicates(subset=['match_id','batsman_runs','is_wicket'])
a.head(5)

# 5. Find all rows where player_dismissed is missing (NaN)
miss=ipl[ipl['player_dismissed'].isna()]
miss.head()

#Adding new columns
ipl['runs']=ipl['total_runs']+ipl['extra_runs']
ipl['runs']

#important dataframe function
ipl['match_id'] = ipl['match_id'].astype('int32')
ipl['match_id']

