# -*- coding: utf-8 -*-
"""Plotting using seaborn2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19scrnHRD62FEJHk38NuFkhN5f0WW96ns
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload()

! ls

! unzip 'archive (7).zip'

tips=pd.read_csv('tips.csv')
tips

from google.colab import files
uploaded = files.upload()

! ls

! unzip 'archive (8).zip'

t=pd.read_csv('Iris.csv')
t

# strip plot
sns.stripplot(data=tips,x='day',y='total_bill', hue='sex',jitter=False)

# using catplot
sns.catplot(data=tips,x='day',y='total_bill',kind='strip',hue='sex',jitter=0.2)

# swarm plot
sns.catplot(data=tips,x='day',y='total_bill',kind='swarm',hue='sex')

# categorical Distribution Plots
# Box plot
sns.boxplot(data=tips,x='day',y='total_bill',hue='sex')

# using catplot
sns.catplot(data=tips,x='day',y='total_bill',kind='box')

# voilin plot
sns.violinplot(data=tips,x='day',y='total_bill',hue='sex',split=True)

# Categorical Estimation
#Bar plot
sns.barplot(data=tips,x='sex',y='total_bill',hue='smoker',estimator=np.min)

# point plot
sns.pointplot(data=tips,x='sex',y='total_bill',hue='smoker',errorbar=None)

# countplot
sns.countplot(data=tips,x='sex',hue='day')

# facetig using catplot
sns.catplot(data=tips,x='sex',y='total_bill',col='smoker',row='time',kind='box')

# Regression plots
# Reg plot -> hue paramter not available
sns.regplot(data=tips,x='total_bill',y='tip')

# lmplot
sns.lmplot(data=tips,x='total_bill',y='tip',hue='sex')

# residplot
sns.residplot(data=tips,x='total_bill',y='tip')

#Multigrid Plots
#Facegrid
g=sns.FacetGrid(data=tips,col='size',height=2.5,col_wrap=3)
g.map(sns.histplot,'total_bill')

# pairplot
sns.pairplot(t,hue='Species')

# Pairgrid
g = sns.PairGrid(t, hue='Species',vars=['SepalWidthCm','PetalWidthCm'])

g.map_diag(sns.histplot)
g.map_upper(sns.kdeplot)
g.map_lower(sns.scatterplot)

g.add_legend()

# JointPlot
import seaborn as sns
sns.jointplot(data=tips,x='total_bill',y='tip',kind='scatter')
plt.show()

#JoinGrid
g=sns.JointGrid(data=tips,x='total_bill',y='tip')
g.plot(sns.kdeplot,sns.violinplot)

# utility functions
sns.get_dataset_names()

#load dataset
sns.load_dataset('planets')

