# -*- coding: utf-8 -*-
"""Plotting using Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c27gw-IZNKFuSuQw4n3jW_7Hitrvclo3

# Plotting using Matplotlib
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# importing dataset
from google.colab import files
uploaded = files.upload()

!ls

import zipfile
with zipfile.ZipFile("iris.zip", 'r') as zip_ref:
    zip_ref.printdir()  # this will print all files inside the zip

import os
os.makedirs("iris_data", exist_ok=True)

with zipfile.ZipFile("iris.zip", 'r') as zip_ref:
    zip_ref.extractall("iris_data")

!ls iris_data

import pandas as pd
columns = ["SepalLength", "SepalWidth", "PetalLength", "PetalWidth", "Species"]
df = pd.read_csv("iris_data/iris.data", names=columns)
df

# Plotting for simple function
price=[48000,54000,67000,47000]
year=[2015,2016,2027,2022]
plt.figure(figsize=(5,3))
# Add title and axis labels
plt.title("plot")
plt.xlabel("values")
plt.ylabel("rows")
plt.plot(price,year)

# Customize the line
# Define your data first
x = [1, 2, 3, 4, 5]
y = [10, 20, 25, 30, 40]
plt.plot(x, y, color='red', linestyle='--', marker='o', linewidth=2)
plt.title("Example Line Plot")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.show()

# Create a bar chart
categories=['A','B','C']
values=[5,7,9]
plt.figure(figsize=(5,3))
plt.bar(categories,values,color='skyblue')
plt.show()

# Create a histogram
import numpy as np
data=np.random.randn(1000)
plt.figure(figsize=(5,3))
plt.hist(data,bins=20,color='orange',edgecolor='black')
plt.show()

# Scatter plot
plt.figure(figsize=(5,3))
plt.scatter(x,y,color='green',marker='.')
plt.show()

# Multiple lines in one plot
plt.figure(figsize=(5,3))
plt.plot(x,label='line 1',marker='o')
plt.plot(y,label='line 2',marker='x')
plt.legend()
plt.show()

# Save figure
plt.figure(figsize=(5,3))
plt.plot([1,2,3],[2,8,4])
plt.savefig("plot.png")
plt.show()

# Pandas + Matplotlib
import pandas as pd
df=pd.DataFrame({
    'Month':['jan','feb','mar'],
    'year':[2018,2019,2022]
})
df.plot(x='Month',y='year',kind='line')
plt.title('sales trend')
plt.show()

# choosing linestyle
plt.figure(figsize=(5,3))
plt.plot(x,y,color="g",linestyle='dashed',linewidth=3)

#nOTE:We can manipulate the width by using linewidth

# using Markers in graphs
import matplotlib.pyplot as plt

x = [1,2,3,4,5]
y = [10,20,25,30,40]
plt.figure(figsize=(5,3))
plt.plot(x,y, marker='o',markersize=8,color="r",linewidth=3, label="Sample Data")
plt.legend(loc='upper left')
plt.title("Line Plot with Markers and Legend")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.show()

#nOTE:markersize=10 → circle has size 10 (default is usually 6)

# Limiting Axes
price=[48000,54000,76000,89000]
year=[2014,2027,2018,2024]
plt.plot(year, price, marker='o', color='blue', linewidth=2)

plt.xlim(2010,2030)
plt.ylim(40000, 90000)

plt.title("Price vs Year")
plt.xlabel("Year")
plt.ylabel("Price")
plt.show()

# grid
price = [48000, 54000, 76000, 89000]
year = [2014, 2027, 2018, 2024]
plt.figure(figsize=(5,3))
plt.plot(year,price,color="g",marker='o',linestyle='solid',linewidth=2,label='price')
plt.grid(True)
# Labels and title
plt.xlabel("Year")
plt.ylabel("Price")
plt.title("Price vs Year with Grid")
plt.legend()

plt.show()

"""# Scatter plots"""

# Simple function
x = np.linspace(-10,0,50)
y= 10*x+3+np.random.randn(50)
plt.figure(figsize=(5,3))
plt.scatter(x,y,color='blue',label='Noisy data')
plt.xlabel('X')
plt.ylabel('y')
plt.title("Scatter plot of y = 10x + 3 with Noise")
plt.grid(True)
plt.legend()
plt.show()

"""# Bar chart"""

children=[10,20,30,40]
colors=['red','blue','green','yellow']
plt.figure(figsize=(5,3))
plt.bar(colors,children)

plt.figure(figsize=(5,3))
plt.barh(colors,children,color='black')

import matplotlib.pyplot as plt
categories = ['A', 'B', 'C', 'D']
boys = [20, 25, 15, 30]
girls = [15, 20, 10, 25]
plt.figure(figsize=(5,3))
# First layer
plt.bar(categories, boys, color='blue', label='Boys')

# Second layer (stacked on top)
plt.bar(categories, girls, bottom=boys, color='pink', label='Girls')

# Labels and title
plt.xlabel("Categories")
plt.ylabel("Count")
plt.title("Stacked Bar Chart Example")
plt.legend()

plt.show()

"""# Histogram


"""

# simple functions
plt.figure(figsize=(5,3))
data=[32,45,67,89,44]
plt.hist(data,bins=[10,25,67,89])

# on some data
import matplotlib.pyplot as plt
import numpy as np
plt.figure(figsize=(5,3))
# Generate sample data
data = np.random.randn(100)
# Create histogram
plt.hist(data)
plt.show()

# logorithmic scale
plt.figure(figsize=(5,3))
plt.plot(y, y)
plt.xscale('log')
plt.yscale('log')
plt.title("Log-Log Scale")
plt.show()

"""# Pie chart"""

# simple data
data=[23,45,100,20,49]
subjects=['eng','science','maths','sst','hindi']
plt.figure(figsize=(5,3))
plt.pie(data,labels=subjects)
plt.show()

# importing dataset
from google.colab import files
uploaded = files.upload()

! ls

#dummy data
subjects = ['English', 'Science', 'Maths', 'Social', 'Hindi']
marks = [78, 92, 88, 74, 81]

# Find Highest Value
highest_mark = max(marks)
highest_subject = subjects[marks.index(highest_mark)]
print("Highest Subject:", highest_subject)
print("Highest Marks:", highest_mark)

# Explode Highest Slice
explode = [0.1 if mark == highest_mark else 0 for mark in marks]
explode

# Custom Colors
colors = ['skyblue', 'orange', 'green', 'pink', 'purple']

#  Change Style
plt.style.use('ggplot')

#  Create Pie Chart
plt.figure(figsize=(5,3))
plt.pie(
    marks,
    labels=subjects,
    colors=colors,
    explode=explode,
    autopct='%1.1f%%',   # show percentage
    shadow=True,
    startangle=90
)

plt.title("Subject Marks Distribution")

# Save Figure
plt.savefig("subject_pie_chart.png")
plt.show()









