# -*- coding: utf-8 -*-
"""Plotting using Seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IHBmn1nJeOJ6Ogk7AxyodGQkCKlWKIdc
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import files
uploaded = files.upload()

! ls

! unzip 'archive (10).zip'

tips=pd.read_csv('tips.csv')
tips

import seaborn as sns
import matplotlib.pyplot as plt
tips = sns.load_dataset('tips')

sns.scatterplot(data=tips,x='total_bill',y='tip')

sns.relplot(data=tips,x='total_bill',y='tip',kind='scatter')

# line plot
ax=sns.lineplot(data=tips,x='total_bill',y='tip',marker='o')
ax.set_title("Distribution area")
plt.show()

# hue,style and size
sns.scatterplot(data=tips, x='total_bill', y='tip', hue='sex', style='smoker', size='size', sizes=(20,200))
plt.title("Tips vs Total Bill by Gender, Smoker and Table Size")
plt.show()
tips

# Facet plots
sns.relplot(data=tips,x='total_bill',y='tip',kind='scatter',col='sex',row='day')

# col wrap
sns.relplot(data=tips,x='total_bill',y='tip',kind='scatter',col='time',col_wrap=3)
plt.show()

# Distribution Plots
plt.figure(figsize=(5,3))
sns.histplot(data=tips,x='total_bill')

plt.figure(figsize=(5,3))
sns.displot(data=tips,x='total_bill',kind='hist')

#countplot
sns.displot(data=tips,x='day',kind='hist')

plt.figure(figsize=(5,3))
sns.displot(data=tips,x='tip',kind='hist',hue='sex',element='step')

from google.colab import files
uploaded = files.upload()

! ls

! unzip 'archive (11).zip'

t=pd.read_csv('Titanic_dataset.csv')
t

sns.kdeplot(data=tips,x='total_bill')

sns.displot(data=tips,x='total_bill',kind='kde',hue='sex',fill=True)

#Rugplot
sns.kdeplot(data=tips,x='total_bill')
sns.rugplot(data=tips,x='total_bill')

#Bivariate Histogram
sns.histplot(data=tips,x='total_bill',y='tip')

# Bivariate Kdeplot
sns.kdeplot(data=tips, x="total_bill", y="tip")
plt.show()

# Matrix Plot
#HeatMap
plt.figure(figsize=(5,3))
sns.heatmap(
    t.corr(numeric_only=True),
    annot=True,
    cmap="coolwarm",
    linewidths=0.5
)

plt.title("Titanic Correlation Heatmap")
plt.show()

# cluster Map
corr = t.corr(numeric_only=True)
sns.clustermap(
    corr,
    cmap="coolwarm",
    annot=True,
    figsize=(5,5)
)
plt.show()