# -*- coding: utf-8 -*-
"""Vectorised String operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1drn1OHhuNMUT69UMuG5DINSrwsi9K_aP

# Vectorised String operations.
"""

from google.colab import files
uploaded = files.upload()

!ls

!unzip "archive (3).zip"

"""# Basic String Transformations"""

# importing dataset
import pandas as pd
df=pd.read_csv('Titanic-Dataset.csv')
df

# 1.lower
df['lower']=df['Name'].str.lower()
df[['Name','lower']].head()

# 2.Uppercase
df['Upper']=df['Name'].str.upper()
df[['Name','Upper']].head()

# 3.Title Case
df['Title']=df['Name'].str.title()
df[['Name','Title']].head()

# 4.Strip Spaces
df['stripped_name']=df['Name'].str.strip()
df['stripped_name']

# Length of Name
df['Length']=df['Name'].str.len()
df[['Name','Length']].head()

# String Searching & Checking
# 1.Contains
df[df['Name'].str.contains('Mr')].head()

# 2.Starts with
df[df['Name'].str.startswith('A')].head(4)

# 3.Ends with
df[df['Name'].str.endswith('n')].head()

# 4.Count
df['count']=df['Name'].str.count('a')
df[['Name','count']]

# Replacing & Modifying Text
df['replace']=df['Name'].str.replace('Mr','Mister',regex=False)
df[['Name','replace']].head()

# Splitting
df['last_name']=df['Name'].str.split(',').str[0]
df[['Name','last_name']].head()

# Extracting
df['extract_title']=df['Name'].str.extract((r',\s*([^\.]+)\.'))
df[['Name','extract_title']].head()

# Advanced Regex Operations
# 1.contains digit
df['contains_digit']=df['Name'].str.contains(r'\d',regex=True)
df['contains_digit'].head()

# 2.Extract 4-digit number
df['y']=df['Name'].str.extract(r'(\d{4})')
df['y'].head()

# 3.Find all capitalized words
df['Capital_words'] = df['Name'].str.findall(r'\b[A-Z]\w+')
df[['Name', 'Capital_words']].head()

"""# Working with DateTime objects"""

# Timestamp objects
ts=pd.Timestamp('2026-02-23 4:00:00')
print(ts)

import pandas as pd

ts = pd.Timestamp('2024-01-15 10:30:00')
print(ts)

#type
type(ts)

# variations
pd.Timestamp('2023-1-5')
pd.Timestamp(2023,1,5)

# Extracting Parts From Timestamp
# year
pd.Timestamp('2020')

# text
pd.Timestamp('23rd February 2026')

"""# Working with E-Commerce Orders Dataset"""

import pandas as pd

data = {
    'Order_ID': range(1, 16),
    'Customer': ['Asha', 'Rahul', 'Priya', 'Vikram', 'Neha',
                 'Arjun', 'Meera', 'Karan', 'Divya', 'Rohan',
                 'Sneha', 'Amit', 'Pooja', 'Varun', 'Anjali'],
    'Order_Date': [
        '2023-01-05 10:30:00',
        '2023-02-14 14:45:00',
        '2023-03-21 09:15:00',
        '2023-04-10 18:20:00',
        '2023-05-01 12:00:00',
        '2023-06-18 16:35:00',
        '2023-07-25 11:10:00',
        '2023-08-30 19:55:00',
        '2023-09-12 08:40:00',
        '2023-10-05 21:15:00',
        '2024-01-01 00:10:00',
        '2024-02-11 13:25:00',
        '2024-03-19 17:50:00',
        '2024-04-22 07:05:00',
        '2024-05-30 22:30:00'
    ],
    'Amount': [2500, 1800, 3200, 1500, 4000,
               2700, 2200, 3100, 2900, 3600,
               5000, 4100, 3300, 2800, 4500],
    'Status': ['Delivered', 'Cancelled', 'Delivered', 'Delivered', 'Pending',
               'Delivered', 'Cancelled', 'Delivered', 'Pending', 'Delivered',
               'Delivered', 'Pending', 'Delivered', 'Cancelled', 'Delivered']
}

df = pd.DataFrame(data)

df.head()

# Convert to DateTime
df['Order_Date']=pd.to_datetime(df['Order_Date'])
df['Order_Date'].head()

# Extracting Date Parts

# 1.Extract Year
df['Year']=df['Order_Date'].dt.year
df['Year'].head(2)

# Extract Month
df['Month']=df['Order_Date'].dt.month
df['Month'].head()

# Extract Day
df['Date']=df['Order_Date'].dt.date
df['Date'].head(3)

# Extract Hour
df['Hour']=df['Order_Date'].dt.hour
df['Hour'].head(3)

# Day Name
df['Day_name']=df['Order_Date'].dt.name
df['Day_name'].head(3)

# Filtering by Date
# Orders in 2023
df[df['Order_Date'].dt.year==2023]

# Orders After March 2023
df[df['Order_Date'] > '2023-03-31']

# Date Calculations

# Difference From Today
df['Days_from_today'] =(pd.Timestamp.now()- df['Order_Date']).dt.days
df['Days_from_today'].head()

# Difference Between Rows
df['Diff']=df['Order_Date'].diff()
df['Diff'].head(5)

# Finding Min / Max Dates
df['Order_Date'].min()
df['Order_Date'].max()

# Sorting by Date
df.sort_values('Order_Date').head(5)

# Grouping by Month (Very Important)
df.groupby(df['Order_Date'].dt.to_period('M'))['Amount'].sum(7)

# Setting Date as Index (Time-Series Mode)
df = df.set_index('Order_Date')
df

# Monthly Resample
df.resample('M')['Amount'].sum()

# Creating Time Categories (Feature Engineering)
def time_of_day(Hour):
    if Hour < 12:
        return 'Morning'
    elif Hour < 17:
        return 'Afternoon'
    elif Hour< 21:
        return 'Evening'
    else:
        return 'Night'

df['Time_Category'] = df['Hour'].apply(time_of_day)
df[['Customer','Status','Time_Category']]

# Rolling Average (Advanced)
df['Rolling']=df['Amount'].rolling(3).mean()
df['Rolling'].head(3)

"""# Pivot tables

"""

# Total Amount by Time Category
pd.pivot_table(df,values='Amount',index='Time_Category',aggfunc='sum')

# Two-Dimensional Pivot
pd.pivot_table(df,values='Amount',index='Month',columns='Status',aggfunc='sum')

# Multiple Aggregations
pd.pivot_table(df,
               values='Amount',
               index='Month',
               columns='Status',
               aggfunc=['sum', 'mean', 'count'])

#Multiple Values
pd.pivot_table(df,
               values=['Amount', 'Order_ID'],
               index='Month',
               aggfunc='count')

# Handling Missing Values
pd.pivot_table(df,
               values='Amount',
               index='Month',
               columns='Status',
               aggfunc='sum',
               fill_value=0)

# Pivot Table vs GroupBy
df.groupby('Month')['Amount'].sum()
pd.pivot_table(df, values='Amount', index='Month', aggfunc='sum')

"""# Datetime Index

"""

#From strings
import datetime as dt
pd.DatetimeIndex(['2023-03-21','2023-07-25'])

#Using python datetime object
pd.DatetimeIndex([('2023-09-12')])

# using timestamps
dates=[pd.Timestamp('2023-09-12'),
       pd.Timestamp('2023-09-13'),
       pd.Timestamp('2023-09-14'),
       pd.Timestamp('2023-09-16')]

idx=pd.DatetimeIndex(dates)
print(idx)

# Using datetimeIndex as series index
s=pd.Series([1,2,3,4],index=dates)
print(s)

"""# Date Range Function"""

# Range of dates
pd.date_range(start='2023-03-21',end='2024-01-01',freq='30D')

# week range of dates
pd.date_range(start='2023-04-16',end='2024-02-11',freq='7D')

# To select specific day in week
pd.date_range(start='2023-04-16',end='2024-02-11',freq='w-Thu')

# To select specific hour
pd.date_range(start='2024-02-11',end='2024-04-22',freq='6H')

"""# Plotting graphs for Time stamp"""

# plotting columns using charts
import matplotlib.pyplot as plt
plt.plot(df['Date'],df['Amount'])

df.columns

# Group by day name and sum Amount
day_sales = df.groupby('Day_name')['Amount'].sum()

# Reorder days to be Monday → Sunday
days_order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
day_sales = day_sales.reindex(days_order)

plt.figure(figsize=(8,3))
plt.bar(day_sales.index, day_sales.values, color='skyblue')
plt.title('Total Sales by Day of Week')
plt.xlabel('Day of Week')
plt.ylabel('Total Amount')
plt.show()





